### ISSUE TITLE
Unexpected java.lang.IllegalStateException

### ISSUE THREAD

**Issue by CrazedProgrammer** [Lignum/CCEmuX#61]
```
OS name: Linux
OS version: 4.10.10-1-ARCH
OS architecture: amd64

JRE vendor: Oracle Corporation
JRE version: 1.8.0_121
JRE architecture: 64

Stack trace: java.lang.IllegalStateException: Component must have a valid peer
	at java.awt.Component$FlipBufferStrategy.flip(Component.java:4092)
	at java.awt.Component$FlipBufferStrategy.show(Component.java:4213)
	at net.clgd.ccemux.rendering.awt.TerminalComponent.render(TerminalComponent.java:117)
	at net.clgd.ccemux.rendering.awt.AWTRenderer.onAdvance(AWTRenderer.java:164)
	at net.clgd.ccemux.emulation.EmulatedComputer.lambda$advance$0(EmulatedComputer.java:161)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at net.clgd.ccemux.emulation.EmulatedComputer.advance(EmulatedComputer.java:161)
	at net.clgd.ccemux.emulation.CCEmuX.lambda$advance$0(CCEmuX.java:125)
	at java.util.HashMap$KeySet.forEach(HashMap.java:932)
	at net.clgd.ccemux.emulation.CCEmuX.advance(CCEmuX.java:123)
	at net.clgd.ccemux.emulation.CCEmuX.run(CCEmuX.java:148)
	at net.clgd.ccemux.init.Launcher.launch(Launcher.java:318)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.clgd.ccemux.init.Launcher.main(Launcher.java:86)
```

**Comment by Lignum** [comment]
yeah that happens

**Comment by Lignum** [comment]
Either way this happens when you create a `BufferStrategy` on a `Component` that hasn't been added to a container, which shouldn't ever happen in this case.

**Comment by Lignum** [comment]
This bug only happens when closing the emulator, so it's not that important that we fix it. Nonetheless, the JavaFX renderer does not have this issue. Shall we mark this as wontfix?

**Comment by dmarcuse** [comment]
Probably - once I get around to finishing the JFX config editor we should make the JFX renderer the default

**Comment by BTCTaras** [comment]
Does this still happen

**Comment by Lignum** [comment]
As far as I know, it still happens occasionally in the AWT renderer. Once JFX is more mature, we can phase AWT out completely, as it's been deprecated for several years now.

**Comment by dmarcuse** [comment]
JFX 11 can be bundled and is available on maven, but it requires Java 10.
